production:
  adapter: postgresql
  encoding: unicode
  database: interactive_forum_prod
  pool: 10
  username: postgres
  password: password
  host: localhost
  port: 5432

development:
  adapter: postgresql
  encoding: unicode
  reconnect: false
  database: quiz_development
  pool: 5
  username: postgres
  password: sharmila
  host: localhost
  port: 5432

test:
  adapter: postgresql
  encoding: unicode
  reconnect: false
  database: quiz_test
  pool: 5
  username: postgres
  password: sharmila
  host: localhost
  port: 5432